Transform: AWS::Serverless-2016-10-31
Description: account dynamodb stream function

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: go1.x
    Tracing: Active
    Architectures:
      - x86_64
    CodeUri: .
    Environment: 
      Variables:
        SERVICE_NAME: !Sub portfolio-${Stage}-stream-function
        REGION: !Ref "AWS::Region"
        STAGE: !Ref Stage
       
  Api:
    TracingEnabled: true

Parameters:
  Stage:
    Type: String

#  SecurityGroupId:
#    Type: String
#  SubnetIds:
#    Type: CommaDelimitedList

  StreamArn:
    Type: String

Resources:
  LambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Lambda policy
      Path: /
      PolicyDocument:
        Version: '2024-04-09'
        Statement:
          -
            Sid: DynamoDBPolicy
            Effect: Allow
            Action:
              - 'dynamodb:*'
            Resource:
              - '*'
          -
            Sid: SNSPolicy
            Effect: "Allow"
            Action:
                - "sns:*"
            Resource: '*'

  AccountStreamFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: main
      Policies:
        - !Ref LambdaPolicy
        - VPCAccessPolicy: {}
      Events:
        AccountDatabase:
          Type: DynamoDB
          Properties:
            Stream: !Ref StreamArn
            StartingPosition: TRIM_HORIZON
